// examples/reactive-react/src/App.tsx
import { useEffect, useState } from "react";
import grab from "grab-url";

type UserState = Partial<{
  name: string;
  email: string;
  isLoading: boolean;
  error: string;
}>;

export default function App() {
  const [userState, setUserState] = useState<UserState>({});

  useEffect(() => {
    // grab hands loading/error/data updates straight to the setState function
    grab("https://jsonplaceholder.typicode.com/users/1", {
      response: setUserState,
    });
  }, []);

  return (
    <main style={{ fontFamily: "system-ui, sans-serif", maxWidth: 480, margin: "3rem auto" }}>
      <h1>User Profile</h1>
      {userState.isLoading && <div>Loading...</div>}
      {userState.error && <div>Error: {userState.error}</div>}
      {userState.name && (
        <div>
          <h2>{userState.name}</h2>
          <p>{userState.email}</p>
        </div>
      )}
    </main>
  );
}

// examples/reactive-vue/src/App.vue
<template>
  <main class="wrap">
    <h1>Search Users</h1>
    <input v-model="searchTerm" @input="searchUsers" placeholder="Search users..." />
    <div v-if="userResults.isLoading" class="loading">Loading users...</div>
    <div v-else-if="userResults.error" class="error">{{ userResults.error }}</div>
    <div v-else class="user-list">
      <div v-for="user in userResults.users" :key="user.id" class="user-card">
        {{ user.name }} — {{ user.email }}
      </div>
    </div>
  </main>
</template>

<script setup lang="ts">
import { ref, reactive } from "vue";
import grab from "grab-url";

// Demo API doesn't implement server-side filtering; this shows the reactive
// loading/error pattern, not a real search backend.
const searchTerm = ref("");
const userResults = reactive<{
  users: Array<{ id: number; name: string; email: string }>;
  isLoading: boolean;
  error: string | null;
}>({
  users: [],
  isLoading: false,
  error: null,
});

const searchUsers = async () => {
  if (searchTerm.value.length < 2) return;

  await grab("https://jsonplaceholder.typicode.com/users", {
    response: userResults,
    query: searchTerm.value,
  });
};
</script>

<style scoped>
.wrap {
  font-family: system-ui, sans-serif;
  max-width: 480px;
  margin: 3rem auto;
}
.user-card {
  padding: 0.5rem 0;
  border-bottom: 1px solid #e5e5e5;
}
.error {
  color: #b91c1c;
}
</style>
